services:
  jellyfin:
    container_name: "${CONTAINER_NAME}"
    image: docker.io/jellyfin/jellyfin:latest
    user: "${USER_ID}:${GROUP_ID}"
    userns_mode: "keep-id:uid=${USER_ID},gid=${GROUP_ID}"
    labels:
      - "io.containers.autoupdate=registry"
    devices:
      - "${DEVICES}"
    volumes:
      - jellyfin-config:/config:Z
      - jellyfin-cache:/cache:Z
      - mnt-hdd:/media/hdd:z
      - mnt-ssd:/media/ssd:z
    network_mode: host
  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr:latest
    labels:
      - "io.containers.autoupdate=registry"
    ports:
      - "5055:5055"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ="Europe/Vienna"
    volumes:
      - jellyseerr-config:/config:Z

volumes:
  mnt-hdd:
    name: "mnt-hdd"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/hdd/media"
  mnt-ssd:
    name: "mnt-ssd"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/ssd/media"
  jellyfin-config:
    name: "vol-jellyfin-config"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/lib/jellyfin/config"
  jellyfin-cache:
    name: "vol-jellyfin-cache"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/lib/jellyfin/cache"
  jellyseerr-config:
    name: "vol-jellyseerr-config"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/var/lib/jellyfin/jellyseerr/config"
 
