services:
  nginx:
    container_name: nginx
    image: docker.io/jc21/nginx-proxy-manager:latest
    labels:
      - "io.containers.autoupdate=registry"
    environment:
      DISABLE_IPV6: "true"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    dns:
        - 9.9.9.9
        - 1.1.1.1
    volumes:
      - /var/lib/nginx/data:/data
      - /var/lib/nginx/letsencrypt:/etc/letsencrypt
